### ISSUE TITLE
No such file or directory error

### ISSUE THREAD

**Issue by korbal** [Fanteria/todotxt-tui#7]
First of all, this is exactly what I needed, I love the project so thank you! 

I've cloned the project, built it all good. Then I copied the file:

_cp target/release/todotxt-tui /usr/local/bin/_

and wanted to execute todotxt-tui but it throws the error No such file or directory (os error 2), no matter where I put the file (obviously in PATH). 

If I cd into the folder and then run it, it throws os error 13. it has exec permission, but even with sudo ./todotxt-tui wouldn't work. Is there anything I'm missing? 

Thank you!

**Comment by Fanteria** [comment]
Thank you for the kind words. I’m not entirely sure, but at first glance, it seems like your config file might be missing. If that’s not the case, the issue could also be with your `toto.txt` or `archive.txt` files. The paths to these files are defined in the config file.

If you're in a hurry, you could try adding them. If not, I’ll attempt to merge the `master` and `dev` branches in the next few days (likely over the weekend), where these errors should be more descriptive. They’re still not pretty, but they should at least indicate which file is missing.

**Comment by korbal** [comment]
Thank you a lot, working now!! :)

**Comment by Fanteria** [comment]
Nice! I'll close this issue. Just a friendly reminder: after merging the `main` branch with `dev`, the configuration paths have changed.
